name: Deploy Book
on:
  push:
    branches:
      - main

env:
  MDBOOK_OUTPUT__HTML__SITE_URL: /mdbook-typst-doc/main/

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.37"
      - uses: typst-community/setup-typst@v3
      - name: Build Book
        run: |
          cd example
          mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/book
          destination_dir: main
